/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "BUCK_BOOST_EN_C.h"
#include "BUCK_BOOST_EN_C_aliases.h"
#include "PDSS_PORT0_RX_CLK.h"
#include "PDSS_PORT0_TX_CLK.h"
#include "PDSS_PORT0_SAR_CLK.h"
#include "DIR_CTRL_C.h"
#include "DIR_CTRL_C_aliases.h"
#include "PWMI_C.h"
#include "Clock_2.h"
#include "PWMI_OUT_C.h"
#include "PWMI_OUT_C_aliases.h"
#include "PDSS_PORT0_BCH_CLK.h"
#include "Bootloadable_1.h"
#include "PDSS_PORT0_FILT_CLK_SEL.h"
#include "PDSS_PORT0_ISINK_CLK.h"
#include "PDSS_PORTX_REFGEN_CLK.h"
#include "EZI2C_1.h"
#include "EZI2C_1_PINS.h"
#include "EZI2C_1_PVT.h"
#include "EZI2C_1_EZI2C.h"
#include "EZI2C_1_EZI2C_PVT.h"
#include "EZI2C_1_BOOT.h"
#include "MasterInput.h"
#include "MasterInput_aliases.h"
#include "MasterInputInt.h"
#include "Clock_1.h"
#include "AUG_TIMER.h"
#include "AUG_ISR.h"
#include "EZI2C_1_SCBCLK.h"
#include "EZI2C_1_sda.h"
#include "EZI2C_1_sda_aliases.h"
#include "EZI2C_1_scl.h"
#include "EZI2C_1_scl_aliases.h"
#include "EZI2C_1_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

